# Generated by Django 4.1.1 on 2022-09-28 14:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_user_country'),
    ]

    operations = [
        migrations.CreateModel(
            name='Retirement',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('address', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=100)),
                ('region', models.CharField(max_length=100)),
                ('zip_code', models.CharField(max_length=15)),
                ('phone_number', models.CharField(max_length=15)),
                ('email', models.EmailField(max_length=254)),
                ('ceremony_data', models.DateField()),
                ('rank', models.CharField(max_length=10)),
                ('branch_of_service', models.CharField(max_length=50)),
                ('years_of_service', models.PositiveSmallIntegerField()),
                ('date_of_retirement', models.DateField()),
                ('additional_information', models.TextField()),
                ('timestamp', models.DateTimeField(auto_now=True)),
                ('is_approved', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('pending', 'pending'), ('declined', 'declined'), ('approved', 'approved')], max_length=10)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='Military_Retirement_Form',
        ),
    ]
