# Generated by Django 4.1.1 on 2022-10-01 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_retirement_delete_military_retirement_form'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='military_id',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
