# Generated by Django 4.1.1 on 2022-10-01 16:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_user_military_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='retirement',
            old_name='ceremony_data',
            new_name='ceremony_date',
        ),
    ]
