# Generated by Django 4.1.1 on 2022-10-02 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_rename_ceremony_data_retirement_ceremony_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='retirement',
            name='status',
            field=models.CharField(choices=[('pending', 'pending'), ('declined', 'declined'), ('approved', 'approved')], default=('pending', 'pending'), max_length=10),
        ),
    ]
