# Generated by Django 4.1.1 on 2022-10-03 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_alter_replacement_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='replacement',
            name='status',
            field=models.CharField(choices=[('pending', 'pending'), ('declined', 'declined'), ('approved', 'approved')], default=('pending', 'pending'), max_length=25),
        ),
    ]
