# Generated by Django 4.1.1 on 2022-10-04 12:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_alter_replacement_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Gift',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('solder_first_name', models.CharField(max_length=100)),
                ('solder_last_name', models.CharField(max_length=100)),
                ('solders_id_number', models.CharField(max_length=100)),
                ('gift_image', models.ImageField(default='gift.png', upload_to='gift.png')),
                ('git_card_number', models.CharField(max_length=100)),
                ('gift_card_amount', models.PositiveSmallIntegerField(default=1)),
                ('gift_card_type', models.CharField(max_length=100)),
                ('timestamp', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('pending', 'pending'), ('declined', 'declined'), ('approved', 'approved')], default=('pending', 'pending'), max_length=25)),
                ('gift_card_to', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gift_to', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
