# Generated by Django 4.1.1 on 2022-10-04 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_alter_retirement_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gift',
            name='gift_image',
            field=models.ImageField(default='gift.png', upload_to='gift'),
        ),
    ]
