# Generated by Django 4.1.1 on 2022-10-07 17:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_alter_gift_gift_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='replacement',
            name='user',
        ),
    ]
