# Generated by Django 4.1.1 on 2022-10-07 18:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_remove_replacement_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='retirement',
            name='user',
        ),
    ]
