# Generated by Django 4.1.1 on 2022-10-07 18:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_remove_retirement_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gift',
            name='gift_card_to',
        ),
        migrations.RemoveField(
            model_name='gift',
            name='user',
        ),
    ]
