# Generated by Django 4.1.1 on 2022-10-11 00:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_remove_gift_gift_card_to_remove_gift_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=600)),
                ('body', models.TextField()),
            ],
        ),
        migrations.RenameField(
            model_name='gift',
            old_name='solder_first_name',
            new_name='solider_first_name',
        ),
        migrations.RenameField(
            model_name='gift',
            old_name='solder_last_name',
            new_name='solider_id_number',
        ),
        migrations.RenameField(
            model_name='gift',
            old_name='solders_id_number',
            new_name='solider_last_name',
        ),
    ]
