# Generated by Django 4.1.1 on 2022-10-11 13:34

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_news_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vacation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('gender', models.CharField(choices=[('male', 'male'), ('female', 'female'), ('other', 'other')], max_length=10)),
                ('date_of_birth', models.DateField()),
                ('solider_id_number', models.CharField(max_length=100)),
                ('mothers_median_name', models.CharField(max_length=30)),
                ('relationship_with_deployed_solider', models.CharField(max_length=30)),
                ('address', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=100)),
                ('region', models.CharField(max_length=100)),
                ('zip_code', models.CharField(max_length=15)),
                ('phone', models.CharField(max_length=15)),
                ('duration_of_vacation', models.CharField(max_length=15)),
                ('reason_for_vacation', models.TextField()),
                ('timestamp', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.RenameField(
            model_name='gift',
            old_name='gift_card_amount',
            new_name='internet_card_amount',
        ),
        migrations.RenameField(
            model_name='gift',
            old_name='gift_image',
            new_name='internet_card_image',
        ),
        migrations.RenameField(
            model_name='gift',
            old_name='gift_card_type',
            new_name='internet_card_number',
        ),
        migrations.RenameField(
            model_name='gift',
            old_name='git_card_number',
            new_name='internet_card_type',
        ),
        migrations.AlterField(
            model_name='news',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
