# Generated by Django 4.1.1 on 2022-10-11 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_vacation_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='vacation',
            name='is_approved',
            field=models.BooleanField(default=False),
        ),
    ]
