# Generated by Django 4.1.1 on 2022-10-11 15:13

from django.db import migrations, models
import django_countries.fields
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_vacation_is_approved'),
    ]

    operations = [
        migrations.CreateModel(
            name='GiftCardRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('amount_of_internet_card', models.PositiveIntegerField()),
                ('recipient_first_name', models.CharField(max_length=30)),
                ('recipient_last_name', models.CharField(max_length=30)),
                ('shipping_address_1', models.CharField(max_length=100)),
                ('shipping_address_2', models.CharField(blank=True, max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('city', models.CharField(max_length=100)),
                ('region', models.CharField(max_length=100)),
                ('zip_code', models.CharField(max_length=15)),
                ('phone', models.CharField(max_length=15)),
                ('country', django_countries.fields.CountryField(max_length=2)),
                ('purchasers_first_name', models.CharField(max_length=30)),
                ('purchasers_last_name', models.CharField(max_length=30)),
                ('billing_address_1', models.CharField(max_length=300)),
                ('billing_address_2', models.CharField(blank=True, max_length=300)),
                ('timestamp', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
