# Generated by Django 4.1.1 on 2022-10-11 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_gift_email_replacement_email_vacation_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='giftcardrequest',
            name='is_approved',
            field=models.BooleanField(default=False),
        ),
    ]
