# Generated by Django 4.1.1 on 2022-10-14 01:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_giftcardrequest_is_approved'),
    ]

    operations = [
        migrations.AlterField(
            model_name='giftcardrequest',
            name='amount_of_internet_card',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=63),
        ),
    ]
