# Generated by Django 4.1.1 on 2022-11-15 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0024_user_date_of_birth_user_deployment_country_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='base',
            field=models.CharField(max_length=250, null=True),
        ),
    ]
