# Generated by Django 4.1.3 on 2022-11-17 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0025_user_base'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='marital_status',
            field=models.CharField(choices=[('single', 'single'), ('relationship', 'relationship'), ('divorce', 'divorce'), ('complicated', 'complicated'), ('married', 'married')], default='single', max_length=15),
        ),
    ]
