# Generated by Django 4.1.3 on 2022-11-17 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0027_alter_user_marital_status_alter_user_rank'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='pay_grade',
            field=models.PositiveIntegerField(blank=True, choices=[('E-1', 'E-1'), ('E-2', 'E-2'), ('E-3', 'E-3'), ('E-4', 'E-4'), ('E-5', 'E-5'), ('E-6', 'E-6'), ('E-7', 'E-7'), ('E-8', 'E-8'), ('E-9', 'E-9'), ('O-1E', 'O-1E'), ('O-2E', 'O-2E'), ('O-3E', 'O-3E'), ('O-4', 'O-4'), ('O-5', 'O-5'), ('O-6', 'O-6'), ('O-7', 'O-7'), ('O-8', 'O-8'), ('O-9', 'O-9'), ('O-10', 'O-10'), ('W-1', 'W-1'), ('W-2', 'W-2'), ('W-3', 'W-3'), ('W-4', 'W-4'), ('W-5', 'W-5')], null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='rank',
            field=models.CharField(max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='weight',
            field=models.DecimalField(blank=True, decimal_places=5, max_digits=5, null=True),
        ),
    ]
